name: zendy
description: Your research partner.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  get: ^4.1.4
  http: ^1.1.0
  animate_do: ^3.0.2
  share: ^2.0.4
  reactive_forms: ^16.0.2
  cupertino_icons: ^1.0.2
  skeleton_text: ^3.0.0
  # cloud_firestore: ^4.8.3
  flutter_libphonenumber: ^2.1.5
  flutter_widget_from_html: ^0.10.3
  webview_flutter: ^4.2.2
  infinite_scroll_pagination: ^3.1.0
  url_launcher: ^6.0.12
  flutter_cached_pdfview: ^0.4.0-nullsafety
  dio: ^5.3.0
  permission_handler: ^10.4.3
  path_provider: ^2.0.5
  connectivity: ^3.0.6
  uuid: ^3.0.5
  awesome_select: ^6.0.0
  # firebase_core: ^2.15.0
  restart_app: ^1.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  image_path: "assets/images/zendy_launcher_ios.png"
  android:
    generate: true
    image_path: "assets/images/zendy_launcher.png"
  ios:
    generate: true
    image_path: "assets/images/zendy_launcher_ios.png"

# flutter_native_splash:
#   image: assets/images/splash_logo.png
#   color: "ffffff"
#   android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf