/// Flutter icons CusIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// SVG sourse files can be find in fonts/iconsSVG
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CusIcons
///      fonts:
///       - asset: fonts/CusIcons.ttf
///
///
import 'package:flutter/widgets.dart';

class CusIcons {
  CusIcons._();

  static const _cusFontName = 'CusIcons';
  static const String _kFontPkg = null;

  static const IconData my_library =
      IconData(0xe800, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData notifications =
      IconData(0xe801, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData paper_add =
      IconData(0xe802, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData saved_search =
      IconData(0xe803, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData search_refine =
      IconData(0xe804, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe805, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe806, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe807, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData arrow_back =
      IconData(0xe808, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData clear =
      IconData(0xe809, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData cite =
      IconData(0xe80a, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe80b, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe80c, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData history_reuse =
      IconData(0xe80d, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe80e, fontFamily: _cusFontName, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xe80f, fontFamily: _cusFontName, fontPackage: _kFontPkg);
}
